apiVersion: v1
kind: ServiceAccount
metadata:
  name: dpu-daemon
  namespace: dpumesh-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dpu-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dpu-pod-reader-binding
subjects:
- kind: ServiceAccount
  name: dpu-daemon
  namespace: dpumesh-system
roleRef:
  kind: ClusterRole
  name: dpu-pod-reader
  apiGroup: rbac.authorization.k8s.io